# Generated by Django 3.0.2 on 2020-01-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCropModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(blank=True, max_length=255)),
                ('y', models.CharField(blank=True, max_length=255)),
                ('width', models.CharField(blank=True, max_length=255)),
                ('height', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
