# Generated by Django 3.0.2 on 2020-01-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_imagecropmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundSubtractModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oimg', models.ImageField(upload_to='images/%Y/%m/%d')),
                ('img', models.ImageField(upload_to='images/%Y/%m/%d')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
