# Generated by Django 3.0.2 on 2020-01-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_backgroundsubtractmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinarizeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r', models.CharField(blank=True, max_length=20)),
                ('g', models.CharField(blank=True, max_length=20)),
                ('b', models.CharField(blank=True, max_length=20)),
                ('k', models.CharField(blank=True, max_length=20)),
                ('img', models.ImageField(upload_to='images/%Y/%m/%d')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
