# Generated by Django 3.0.2 on 2020-01-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0004_binarizemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
